spring:
  application:
    name: slack-service
  datasource:
    url: jdbc:postgresql://3.39.10.27:5430/themeparkdb
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: slack_service
  data:
    redis:
      host: 3.39.10.27
      port: 6379
      username: default
      password: systempass
  kafka:
    consumer:
      bootstrap-servers: 3.39.10.27:8088
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8006

slack:
  bot:
    token: ${SLACK_TOKEN}
  admin:
    id: C08NM9CQ3SA

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'