global:
  scrape_interval: 15s  # 메트릭 수집 주기

scrape_configs:
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ]  # Eureka Server 메트릭 엔드포인트

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Gateway Service 메트릭 엔드포인트

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8001']  # User Service 메트릭 엔드포인트

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8002']  # Order Service 메트릭 엔드포인트

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8004']  # Product Service 메트릭 엔드포인트

  - job_name: 'themepark-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8005']  # ThemePark Service 메트릭 엔드포인트

  - job_name: 'slack-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8006']  # Slack Service 메트릭 엔드포인트
