###
POST http://localhost:8080/v3/orders
Content-Type: application/json
Authorization: {{accessToken}}

{
  "order" : {
    "slackId" : "1234",
    "productId" : "72106dbc-b8d6-4dbf-8deb-6d4ce7b7feda",
    "amount" : 5000
  }
}


