###
POST http://localhost:8080/v1/orders
Content-Type: application/json
Authorization: {{accessToken}}

{
  "order" : {
    "slackId" : "1234",
    "productId" : "e97ac418-79d5-4282-8fde-c072b2d431e6",
    "amount" : 5000
  }
}


