spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://3.39.10.27:5430/themeparkdb
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_service
  data:
    redis:
      host: 3.39.10.27
      port: 6379
      username: default
      password: systempass
  jwt:
    secret: "MeyhsO2FjOuniO2MjO2BrOyLnO2BrOumv+2CpOyeheuLiOuLpOyVhOyVhOyVhOyVhOyVhOyVhA=="

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'