spring:
  application:
    name: user-service
  jwt:
    secret: "MeyhsO2FjOuniO2MjO2BrO2Mn+2MhQ=="
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8001