spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order-payment
    username: dj
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

toss:
  secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  clientKey: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm