spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://51.20.67.219:5430/themeparkdb
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: 51.20.67.219
      port: 6379
      username: default
      password: systempass

  kafka:
    bootstrap-servers: 51.20.67.219:8088
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    zipkin:
      endpoint: http://51.20.67.219:9411/api/v2/spans

toss:
  secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  clientKey: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
