# application-test.yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

toss:
  secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  clientKey: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm