POST http://localhost:8080/v1/hashtags
Content-Type: application/json

{
  "hashtag": {
    "name": "드라마틱"
  }
}

####

GET http://localhost:8080/v1/hashtags/1d57d230-3fe2-4b9b-ae80-d69f73a117b2

###

GET http://localhost:8080/v1/hashtags?name=짜릿한&name=신나는

###

PUT http://localhost:8080/v1/hashtags/f20d7a0c-0872-4b95-9440-dc2bd1c49cc1
Content-Type: application/json

{
  "hashtag": {
    "name": "흥미로운"
  }
}

###

DELETE http://localhost:8080/v1/hashtags/1d57d230-3fe2-4b9b-ae80-d69f73a117b2

