### 1-1. 슬랙 이벤트 타입 CREATE
POST http://localhost:8080/v1/slack-event-types
Content-Type: application/json
Authorization: {{accessToken}}

{
  "slackEventType": {
    "name": "WAITING_CALL"
  }
}

### 2-1. 슬랙 템플릿 CREATE
POST http://localhost:8080/v1/slack-templates
Content-Type: application/json
Authorization: {{accessToken}}
// relatedName은 {{relatedName}}으로 전달해야 합니다.

{
  "slackTemplate": {
    "slackEventTypeId": "5edff6f0-b211-4fb4-b106-641a8fcfe8d1",
    "content": "relatedName 번 손님 지금 입장해주세요."
  }
}

### 3-2. 슬랙 CREATE + 사용자 DM 전송
POST http://localhost:8080/v1/slacks
Content-Type: application/json
Authorization: {{accessToken}}

{
  "slack": {
    "slackEventTypeId": "5edff6f0-b211-4fb4-b106-641a8fcfe8d1",
    "relatedName": "8월 한정 20% 할인",
    "target": {
      "slackId": "U08L3T2DTCP",
      "type": "USER_DM"
    }
  }
}