POST http://localhost:8080/v1/auth/login
Content-Type:application/json

{
  "user": {
    "username": "asdf",
    "password": "asdkasjdh1123"
  }
}
> {%
    client.global.set("accessToken", response.headers.valueOf("ACCESS_TOKEN"))
%}

###

POST http://localhost:8080/v1/themeparks
Content-Type: application/json
Authorization: {{accessToken}}

{
  "themepark":
    {
      "name": "알라딘",
      "description": "아라비안 나이트",
      "type": "RIDE",
      "heightLimit": "130~180cm",
      "operationStartTime": "10:00",
      "operationEndTime": "18:00",
      "supervisor": true,
      "hashtagList": [{
        "hashtagId": "376df3fd-f172-4046-8bd2-9ab22b9c79cd"
      },{
        "hashtagId": "06b9986a-f997-49b0-8d7e-3d9dad67943b"
      }
      ]
    }
}

###

GET http://localhost:8080/v1/themeparks/3dca02ed-55c7-4f7c-9e5b-2126f9b2139f

###

GET http://localhost:8080/v1/themeparks?description=슝슝 놀이기구입니다.3

###

PUT http://localhost:8080/v1/themeparks/7949401a-a67e-41cf-a5e3-192ad62d81f8
Content-Type: application/json
Authorization: {{accessToken}}

{
  "themepark": {
    "heightLimit": "140~180cm",
    "hashtagList": [
      {
        "hashtagId": "f5e49e7d-3baf-478f-bb36-d70b66330f79"
      },
      {
        "hashtagId": "f5e49e5d-3baf-478f-bb36-d70b66330f79"
      }
    ]
  }
}

###

DELETE http://localhost:8080/v1/themeparks/1bce86d2-1afb-4e80-994e-a1fb4d92aaf9
Authorization: {{accessToken}}
