POST http://localhost:8080/v1/auth/login
Content-Type:application/json

{
  "user": {
    "username": "hgfhbhj",
    "password": "asdkasjdhs1123"
  }
}
> {%
    client.global.set("accessToken", response.headers.valueOf("ACCESS_TOKEN"))
%}

###

POST http://localhost:8080/v1/waitings
Content-Type: application/json
Authorization: {{accessToken}}

{
  "waiting": {
    "themeparkId": "4b1f595e-18e0-4e08-8277-8963dfd1d06b"
  }
}

###

GET http://localhost:8080/v1/waitings/8599d801-8e69-4204-872d-ebe13916e0c7
Authorization: {{accessToken}}

###

GET http://localhost:8080/v1/waitings?themeparkId=f5220852-59fe-4894-8fc4-200bd1419872
Authorization: {{accessToken}}

###

POST http://localhost:8080/v1/waitings/83fd502d-1ff3-47bd-8915-4ca4bd9433d1/done
Authorization: {{accessToken}}

###

POST http://localhost:8080/v1/waitings/8599d801-8e69-4204-872d-ebe13916e0c7/cancel
Authorization: {{accessToken}}

###

DELETE http://localhost:8080/v1/waitings/8599d801-8e69-4204-872d-ebe13916e0c7
Authorization: {{accessToken}}

###

POST http://localhost:8080/v1/waitings/e5fe4018-5707-4b26-abd4-c5cfaf95fa4b/call
Authorization: {{accessToken}}

